name = "rive-casparcg-generator"
main = "src/worker.mjs"                 # <— your Worker entry file
compatibility_date = "2025-09-26"       # must be ≥ 2024-09-23 for Node compat
compatibility_flags = ["nodejs_compat"] # Node APIs in Workers

[assets]                                 # <— serves /public as static files
directory = "public"
# binding = "ASSETS"                     # optional: if you want env.ASSETS.fetch()
